### ISSUE TITLE
Hi from Gitcoin

### ISSUE THREAD

**Issue by owocki** [fulldecent/su-squares-bounty#4]
hi from [Gitcoin](https://gitcoin.co/)!

mind if we promote this bounty program on the gitcoin slack?  looks like i might be a day late to really get invovled.... but would like to try.. we have a few thousand members of our network and they are all hungry for 🐛 squashing oppy's

**Comment by fulldecent** [comment]
Thank you! Yes, much appreciated!

**Comment by fulldecent** [comment]
If you give ma a link to your announcement I can feature it here too!

**Comment by owocki** [comment]
here ya go => https://twitter.com/GetGitcoin/status/969631280697458688
