### ISSUE TITLE
_transfer doesn't clear approval

### ISSUE THREAD

**Issue by paulbarclay** [fulldecent/su-squares-bounty#5]
Without clearing approval, I can steal back a token I've transferred to you - call approve(me, id), call transferFrom(me, you, id), then I can still call transferFrom(me, anyone, id).

**Comment by fulldecent** [comment]
Very nice, thank you.

**Comment by fulldecent** [comment]
Thanks again for your help. I believe we have fixed this with afe1a358eaa9fcd46f2c5d0e410fe392118c0a99.

And this is definitely worth a square. Please email me if I may grant you a square.
