### ISSUE TITLE
Can't get the same interfaceID for ERC721

### ISSUE THREAD

**Issue by MoMannn** [fulldecent/su-squares-bounty#6]
I am trying to get the same interfaceID for ERC721 as you: 0x80ac58cd
But I cannot get it..
This is how I'm trying to reproduce it:
import "./ERC721.sol";

contract Selector {
    function calculateSelector() public pure returns (bytes4) {
        ERC721 i;
        return i.balanceOf.selector
           ^ i.ownerOf.selector
           ^ bytes4(keccak256("safeTransferFrom(address,address,uint256,bytes)"))
           ^ bytes4(keccak256("safeTransferFrom(address,address,uint256)"))
           ^ i.transferFrom.selector
           ^ i.approve.selector
           ^ i.setApprovalForAll.selector
           ^ i.getApproved.selector
           ^ i.isApprovedForAll.selector;
    }
}

**Comment by fulldecent** [comment]
Thanks for following up quickly on this.

Can you please add your notes on how you were able to confirm this. I will be helpful to others searching this issue.

And, of course, thank you for your interest in this project!
