### ISSUE TITLE
Launch new bounty

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/su-squares-bounty#7]
This bounty just launched again. I'm only making an issue so I can mention some people:

Ping @sz-piotr @owocki @paulbarclay @momannn.

We are going to redeploy the contract to make fixes an a result of this bounty, and also the small changes made to ERC-721 to get to final status.

For those of you that earned squares in the last competition, I will copy your squares over to the new deployment. And I hope you will personalize them this time! Gosh, too much white.

Cheers,
Will

**Comment by sz-piotr** [comment]
Maybe change the area to be 10x10. This way you still get ten thousand squares (pixels) but the images will be much larger.

**Comment by fulldecent** [comment]
So sell a 100 squares at once? I like your sales spirit!

**Comment by fulldecent** [comment]
Bounty is over, closing issue
