### ISSUE TITLE
Unnecessary `payable` functions

### ISSUE THREAD

**Issue by dafky2000** [fulldecent/su-squares-bounty#8]
Are these functions `payable` for a reason I am missing?

```
function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
function approve(address _approved, uint256 _tokenId) external payable;
```

**Comment by fulldecent** [comment]
They work the same whether you send money to them or not.

**Comment by fulldecent** [comment]
But if people want to send value to the contract for some reason then I don't see a good reason to stop them!

**Comment by fulldecent** [comment]
But actually, the biggest reason is just for convenience because this is written in Solidity 0.4.24 which does not support implementing a payable function (like the ERC-721 spec) with a non-payable function (like Su Squares implementation). Rest assured though that Solidity 0.5.0 will support that.
